{{- if .Values.gitSecrets.enabled | default false  }}
{{- range $secretName, $secretConfig := .Values.gitSecrets.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$secretName}}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  # Values are base64 encoded
  type: {{ $secretConfig.type | toString | b64enc }}
  url: {{ $secretConfig.url | toString | b64enc }}
  githubAppID: {{ $secretConfig.githubAppID | toString | b64enc }}
  githubAppInstallationID: {{ $secretConfig.githubAppInstallationID | toString | b64enc }}
  githubAppPrivateKey: {{ $secretConfig.githubAppPrivateKey | toString  }}
---
{{- end }}
{{- end }}
