apiVersion: v2
name: application-sets
description: Fleet management ApplicationSets
type: application
version: 0.1.0
dependencies:
  - name: addons
    version: "{{ .Values.addons.version }}"
    repository: "file://./charts/addons"
    condition: addons.use
  - name: ack
    version: "{{ .Values.ack.version }}"
    repository: "file://./charts/ack/package"
    condition: ack.use
  - name: monitoring
    version:  "{{ .Values.monitoring.version }}"
    repository: "file://./charts/monitoring"
    condition: monitoring.use
  - name: resources
    version: "{{ .Values.esources.version }}"
    repository: "file://./charts/resources"
    condition: resources.use