# Test values for globalValuesObject functionality
globalValuesObject:
  commonLabels:
    app.kubernetes.io/part-of: "eks-fleet-management"
    managed-by: "gitops-fleet-management"
    team: "platform"
    global-test: "true"
  commonAnnotations:
    managed-by: "gitops-fleet-management"
    global-annotation: "test-value"

# Enable merging from component files
mergeValues:
  addons: 
    use: true

# Test components to verify globalValuesObject merging
test-component-1:
  enabled: true
  chartName: test-chart-1
  namespace: test-ns-1
  defaultVersion: "1.0.0"
  chartRepository: "https://example.com/charts"
  valuesObject:
    component-specific:
      setting1: "value1"
      setting2: "value2"
    commonLabels:
      component-label: "component-1"
      # This should merge with global commonLabels

test-component-2:
  enabled: true
  chartName: test-chart-2
  namespace: test-ns-2
  defaultVersion: "2.0.0"
  chartRepository: "https://example.com/charts"
  valuesObject:
    component-specific:
      setting3: "value3"
    commonAnnotations:
      component-annotation: "component-2"
      # This should merge with global commonAnnotations

# Component without valuesObject to test global-only scenario
test-component-3:
  enabled: true
  chartName: test-chart-3
  namespace: test-ns-3
  defaultVersion: "3.0.0"
  chartRepository: "https://example.com/charts"
  # No valuesObject - should only get global values

# Disabled component - should not appear in output
test-component-disabled:
  enabled: false
  chartName: test-disabled
  namespace: test-disabled-ns

# Common configuration
syncPolicy:
  automated:
    selfHeal: true
    allowEmpty: true
    prune: true

repoURLGit: 'https://github.com/test/repo.git'
repoURLGitRevision: 'main'
repoURLGitBasePath: 'test-path'
valueFiles:
  - 'defaults'
  - 'environments/test'
