apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: efsstorage.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: EfsStorage
    spec:
      name: string | default=ingress-triangle
  resources:
  - id: efs
    template:
      apiVersion: acm.services.k8s.aws/v1alpha1
      kind: Certificate
      metadata:
        name: ${schema.spec.name}-cert
      spec:
        domainName: ${schema.spec.domainName}.${schema.spec.domain}
        domainValidationOptions:
          - domainName: ${schema.spec.domainName}.${schema.spec.domain}
            validationDomain: ${schema.spec.domain}
            targetPort: 80