secretStore:
  enabled: false
  kind: "SecretStore"
  name: "aws-secrets-manager"
  region: ""
  role: ""

externalSecret:
  enabled: false
  secretStoreRefName: "fleet-eks-secret-store"
  secretStoreRefKind: "SecretStore"
  server: "self"
  secretManagerSecretName: ""
  clusterName: ""

gitExternalSecrets:
  enabled: false
  secretStoreRefName: "fleet-eks-secret-store"
  secretStoreRefKind: "SecretStore"
  externalSecrets:
    addons:
      gitUrl: ""
      secretName: "git-addons"
      secretManagerSecretName: ""

secret:
  enabled: false
  cluster_name: ""
  annotations: {}
  labels: {}

gitSecrets:
  enabled: false
  secrets:
    git-addons:
      type: git
      url: ""
      githubAppID: ""
      githubAppInstallationID: ""
      githubAppPrivateKey: ""
    git-resources:
      type: git
      url: ""
      githubAppID: ""
      githubAppInstallationID: ""
      githubAppPrivateKey: ""

ecrAuthenticationToken:
  enabled: false
  region: eu-west-2
  name: "ecr-token"
  namespace: "argocd"
  # The Secret Name created by terraform on cluster creation
  secretName: "argocd-ecr-credentials"

