podIdentityPolicyCreate: true
podIdentityRole:
  description: "EFS CSI Default Role"
  permissionsBoundary: "arn:aws:iam::008971676728:policy/spoke-test-auto-workload2-ack-bountries"
podIdentityAssociation:
  serviceAccounts:
      - efs-csi-controller-sa
      - efs-csi-node-sa
podIdentityPolicy:
  description: "EFS CSI Default Policy"
  policies:
    - resourceType: ec2
      resourceName: "*"
      actions:
        - "ec2:DescribeAvailabilityZones"
    - resourceType: elasticfilesystem
      resourceName: "*"
      actions:
        - "elasticfilesystem:DescribeAccessPoints"
        - "elasticfilesystem:DescribeFileSystems"
        - "elasticfilesystem:DescribeMountTargets"
        - "elasticfilesystem:DescribeMountTargetSecurityGroups"
    - resourceType: elasticfilesystem
      resourceName: "*"
      actions:
        - "elasticfilesystem:CreateAccessPoint"
        - "elasticfilesystem:DeleteAccessPoint"
        - "elasticfilesystem:CreateFileSystem"
        - "elasticfilesystem:CreateMountTarget"
        - "elasticfilesystem:ModifyMountTargetSecurityGroups"