# Monitoring Addons
cw-prometheus:
  enabled: true
  enableAckPodIdentity: false
  namespace: '{{default "amazon-cloudwatch" (index .metadata.annotations "cw_prometheus_namespace")}}'
  chartName: cw-prometheus
  defaultVersion: "0.1.0"
  path: 'charts/cw-prometheus'
  selector:
    matchExpressions:
      - key: enable_cw_prometheus
        operator: In
        values: ['true']
