# Debug template to test coalesce behavior
{{- if .Values.debug }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-coalesce-test
data:
  # Test the standard coalesce function
  standard-coalesce: "{{ coalesce .Values.bootstrap.groups.addons.preserveResourcesOnDeletion .Values.argocd.preserveResourcesOnDeletion "fallback" }}"

  # Test our custom boolean coalesce helper
  bool-coalesce: "{{ include "fleet-common.boolCoalesce" (list .Values.bootstrap.groups.addons.preserveResourcesOnDeletion .Values.argocd.preserveResourcesOnDeletion true) }}"

  # Test getValue helper
  get-value: "{{ include "fleet-common.getValue" (dict "values" (list .Values.bootstrap.groups.addons.preserveResourcesOnDeletion .Values.argocd.preserveResourcesOnDeletion "default-fallback")) }}"

  # Check individual values
  config-value: "{{ .Values.bootstrap.groups.addons.preserveResourcesOnDeletion }}"
  argocd-value: "{{ .Values.argocd.preserveResourcesOnDeletion }}"

  # Check if values exist
  config-exists: "{{ if hasKey .Values.bootstrap.groups.addons "preserveResourcesOnDeletion" }}true{{ else }}false{{ end }}"
  argocd-exists: "{{ if hasKey .Values.argocd "preserveResourcesOnDeletion" }}true{{ else }}false{{ end }}"

  # Test with explicit false value
  explicit-false-test: "{{ include "fleet-common.boolCoalesce" (list false true "fallback") }}"
  explicit-nil-test: "{{ include "fleet-common.boolCoalesce" (list nil false "fallback") }}"
{{- end }}
