# Fleet Management Configuration
# This chart replaces the static bootstrap files and provides a values-driven approach

# Global Configuration
argocd:
  namespace: argocd

chartRepo: "1234567890.dkr.ecr.eu-west-2.amazonaws.com"

# Bootstrap ApplicationSets Configuration
# These replace the files in fleet/bootstrap/
bootstrap:
  enabled: false
  
  # Global defaults - these will be used unless overridden at the group level
  global:
    globalValuesPath: bootstrap/defaults/
    globalSelectors:
      fleet_member: hub-cluster
    preserveResourcesOnDeletion: false
    fleetMember: hub-cluster
    chartName: application-sets
    chartPath: charts/application-sets
    useSelectors: false
    useVersionSelectors: true
    versionsPath: bootstrap/versions/applicationSets.yaml
    repoNames: ["addons"]  # Repository names to use for all groups
    project: default
    syncPolicy:
      automated:
        selfHeal: false
        allowEmpty: true
        prune: false
      retry:
        limit: 100
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  # Group-specific configurations - override global defaults as needed
  groups:
    addons:
      enabled: true
      applicationSets:
        argocd:
          enabled: true
      mergeValues:
        addons: 
          use: true
        ack:
          use: true
      # Uses all global defaults including mergeValues, globalSelectors, valueFiles
    resources:
      enabled: false
      preserveResourcesOnDeletion: false  # Override global default
      mergeValues:
        resources: 
          use: true
      syncPolicy:
        automated:
          selfHeal: true  # Override global default
          prune: true     # Override global default
    monitoring:
      enabled: false
      useSelectors: false  # Override global default
      # Custom global selectors for monitoring
      globalSelectors:
        fleet_member: hub-cluster
      # Custom merge values for monitoring
      repoNames: ["addons", "resources"]
      mergeValues:
        monitoring: 
          use: true

# Fleet Bootstrap Configuration
# These replace the logic in fleet/fleet-bootstrap/
fleetBootstrap:
  enabled: true
  
  # Fleet Registration
  registration:
    enabled: false
  registrationName: fleet-registration-v2
  applicationName: fleet-v2
  project: default
  sourcePath: fleet-bootstrap
  preserveResourcesOnDeletion: true
  clusterSelector:
    fleetMember: hub-cluster
  syncPolicy:
    automated: {}
  
  # Test ApplicationSet for validation
  testApplicationSet:
    enabled: false
    preserveResourcesOnDeletion: false
    project: default
    namespace: fleet-test
    clusterSelector:
      fleetMember: hub-cluster
      test-cluster: "true"
    syncPolicy:
      automated:
        selfHeal: true
        allowEmpty: true
        prune: false
      retry:
        limit: 3
  
  # Fleet Secrets Management
  secrets:
    enabled: true
    name: fleet-hub-secrets
    applicationName: fleet-secrets
    project: default
    sourcePath: fleet-bootstrap
    namespace: platform-system
    releaseName: fleet-secrets
    preserveResourcesOnDeletion: true
    clusterSelector:
      fleetMember: hub-cluster
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  
  # Fleet Member Bootstrap
  memberBootstrap:
    enabled: false
    staticPath: bootstrap/defaults
    name: fleet-members-bootstrap
    project: default
    sourcePath: fleet-bootstrap/members-application-sets
    preserveResourcesOnDeletion: true
    clusterSelector:
      fleetMember: hub-cluster
    directory:
      recurse: true
    syncPolicy:
      automated:
        selfHeal: true
        prune: true

# Version Management (replaces fleet/bootstrap/versions/applicationSets.yaml)
releases:
  addons:
    - type: "default"
      use_helm_repo_path: "true"
      chartRepo: "471112582304.dkr.ecr.eu-west-2.amazonaws.com"
      ecrChartName: "application-sets"
      version: 0.3.1
    - type: "release1"
      use_helm_repo_path: "true"
      chartRepo: "471112582304.dkr.ecr.eu-west-2.amazonaws.com"
      ecrChartName: "application-sets"
      version: 0.3.1
  monitoring:
    - type: "default"
      use_helm_repo_path: "true"
      chartRepo: "471112582304.dkr.ecr.eu-west-2.amazonaws.com"
      ecrChartName: "application-sets"
      version: 0.1.0
  resources:
    - type: "default"
      use_helm_repo_path: "false"
      ecrChartName: "application-sets"
      chartRepo: "471112582304.dkr.ecr.eu-west-2.amazonaws.com"
      version: 0.3.1
  fleet:
    - type: "default"
      use_helm_repo_path: "true"
      ecrChartName: "application-sets"
      chartRepo: "471112582304.dkr.ecr.eu-west-2.amazonaws.com"
      version: 0.3.1