syncPolicy:
  automated:
    selfHeal: false
    allowEmpty: true
    prune: false
  retry:
    limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
    backoff:
      duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      factor: 2 # a factor to multiply the base duration after each failed retry
      maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true  # Big CRDs.
syncPolicyAppSet:
  preserveResourcesOnDeletion: true
repoURLGit: '{{.metadata.annotations.addons_repo_url}}'
repoURLGitRevision: '{{.metadata.annotations.addons_repo_revision}}'
repoURLGitBasePath: '{{.metadata.annotations.addons_repo_basepath}}'
valueFiles:
  - default/addons
  - clusters/{{.nameNormalized}}/addons
useValuesFilePrefix: true
valuesFilePrefix: '{{.metadata.labels.tenant}}/'
useSelectors: false
karpenter-resources:
  enabled: true
  chartName: karpenter-resources
  defaultVersion: "1.0.0"
  path: 'charts/karpenter-resources'
  namespace: karpenter-resources
  selector:
    matchExpressions:
      - key: enable_karpenter_resources
        operator: In
        values: ['true']
  valuesObject:
    nodeClases:
      role: '{{.metadata.annotations.karpenter_node_iam_role_name}}'
      clusterName: '{{.metadata.annotations.aws_cluster_name}}'
pod-identity:
  gitMatrix: true
  enabled: true
  chartName: pod-identity
  defaultVersion: "1.0.0"
  path: 'charts'
  matrixPath: '{{.metadata.annotations.resources_repo_basepath}}{{.metadata.labels.tenant}}/clusters/{{.name}}/resources/pod-identities/*.yaml'
  namespace: '{{default "pod-identity" (index .metadata.annotations "pod-identity")}}'
  selector:
    matchExpressions:
      - key: enable_pod_identity_resources
        operator: In
        values: ['true']
  valuesObject:
    create: true
    region: '{{.metadata.annotations.aws_region}}'
    accountId: '{{.metadata.annotations.aws_account_id}}'
    podIdentityAssociation:
      clusterName: '{{.metadata.annotations.aws_cluster_name}}'
      namespace: '{{.namespace}}'