{{- range .Values.applicationsets }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          {{- range .paths }}
          - path: {{ .path }}
          {{- end }}
  template:
    metadata:
      name: '{{ .name }}-{{ "{{path}}" }}'
    spec:
      project: {{ .project | default "default" }}
      source:
        repoURL: {{ .repoURL }}
        targetRevision: {{ .targetRevision | default $.Values.applicationsetDefaults.targetRevision }}
        path: '{{ "{{path}}" }}'
      destination:
        server: {{ .destination.server | default "https://kubernetes.default.svc" }}
        namespace: {{ .destination.namespace | default $.Values.applicationsetDefaults.destination.namespace }}
      {{- if .syncPolicy }}
      syncPolicy:
        {{- toYaml .syncPolicy | nindent 8 }}
      {{- else if $.Values.applicationsetDefaults.syncPolicy }}
      syncPolicy:
        {{- toYaml $.Values.applicationsetDefaults.syncPolicy | nindent 8 }}
      {{- end }}
---
{{- end }} 